Repository pankod/superplate, pull requests merged in 2021-05, with the labels that each got.

#242 Add gitignore file on CRA template.
  templates/react/gitignore
Labels: auto-merge, pr-ready, review-required

#248 React docs fixes
  README.MD
  documentation/docs/development/creating-a-plugin.md
  documentation/docs/development/how-it-works.md
  documentation/docs/development/references.md
  documentation/docs/quick-start.md
  documentation/docusaurus.config.js
  documentation/static/img/cli.gif
  images/available.png
  images/cli.gif
  images/integrations.png
Labels: auto-merge, review-required

#249 Check if `yarn` installed before asking
  package.json
  src/Helper/binary/index.spec.ts
  src/Helper/binary/index.ts
  src/Helper/index.ts
  src/saofile.ts
Labels: auto-merge, pr-ready
