Repository pankod/superplate, pull requests merged in 2021-02, with the labels that each got.

#198 Refactor docs
  documentation/blog/2019-05-28-hola.md
  documentation/blog/2019-05-29-hello-world.md
  documentation/blog/2019-05-30-welcome.md
  documentation/docs/apollo-graphql.md
  documentation/docs/axios.md
  documentation/docs/bundle-analyzer.md
  documentation/docs/ci/github-actions.md
  documentation/docs/ci/travis.md
  documentation/docs/development/creating-a-plugin.md
  documentation/docs/development/how-it-works.md
  documentation/docs/development/references.md
  documentation/docs/doc1.md
  documentation/docs/doc2.md
  documentation/docs/doc3.md
  documentation/docs/docker.md
  documentation/docs/e2e-testing/cypress.md
  documentation/docs/e2e-testing/wdio.md
  documentation/docs/env.md
  documentation/docs/fetch.md
  documentation/docs/graphql-request.md
  documentation/docs/i18n/next-i18next.md
  documentation/docs/i18n/next-translate.md
  documentation/docs/quick-start.md
  documentation/docs/storybook.md
  documentation/docs/svgr.md
  documentation/docs/testing/enzyme.md
  documentation/docs/testing/jest.md
  documentation/docs/testing/testing-library.md
  documentation/docusaurus.config.js
  documentation/sidebars.js
Labels: auto-merge, review-required

#203 Add descriptions
  documentation/docs/antd.md
  documentation/docs/apollo-graphql.md
  documentation/docs/bootstrap.md
  documentation/docs/bundle-analyzer.md
  documentation/docs/chakra-ui.md
  documentation/docs/ci/github-actions.md
  documentation/docs/ci/travis.md
  documentation/docs/css.md
  documentation/docs/docker.md
  documentation/docs/e2e-testing/cypress.md
  documentation/docs/e2e-testing/wdio.md
  documentation/docs/env.md
  documentation/docs/fetch.md
  documentation/docs/graphql-request.md
  documentation/docs/hooks/react-query.md
  documentation/docs/hooks/react-use.md
  documentation/docs/hooks/swr.md
  documentation/docs/i18n/next-i18next.md
  documentation/docs/i18n/next-translate.md
  documentation/docs/linter/eslint.md
  documentation/docs/linter/lint-staged.md
  documentation/docs/linter/prettier.md
  documentation/docs/reverse-proxy.md
  documentation/docs/scss.md
  documentation/docs/state-management/mobx.md
  documentation/docs/state-management/recoil.md
  documentation/docs/state-management/redux-toolkit.md
  documentation/docs/storybook.md
  documentation/docs/styled-components.md
  documentation/docs/svgr.md
  documentation/docs/tailwind.md
  documentation/docs/testing/enzyme.md
  documentation/docs/testing/jest.md
  documentation/docs/testing/testing-library.md
Labels: auto-merge, pr-ready

#202 Update Chakra UI docs
  documentation/docs/chakra-ui.md
Labels: auto-merge, pr-ready

#199 add postcss config to tailwind docs
  documentation/docs/tailwind.md
Labels: auto-merge, pr-ready

#200 add example test jest
  documentation/docs/testing/jest.md
Labels: auto-merge, pr-ready

#201 match order with prompts
  documentation/sidebars.js
Labels: auto-merge, pr-ready

#184 Landing design
  documentation/docusaurus.config.js
  documentation/src/css/custom.css
  documentation/src/features.js
  documentation/src/pages/index.js
  documentation/src/pages/styles.module.css
  documentation/static/img/antd.svg
  documentation/static/img/apollo.svg
  documentation/static/img/bootstrap.svg
  documentation/static/img/chakra-ui.svg
  documentation/static/img/code.svg
  documentation/static/img/css.svg
  documentation/static/img/cypress.svg
  documentation/static/img/docker.svg
  documentation/static/img/enzyme.png
  documentation/static/img/eslint.svg
  documentation/static/img/favicon.ico
  documentation/static/img/footer_icon.png
  documentation/static/img/github-actions.svg
  documentation/static/img/graphql.svg
  documentation/static/img/i18next.svg
  documentation/static/img/jest.svg
  documentation/static/img/mobx-state-tree.svg
  documentation/static/img/mobx.svg
  documentation/static/img/next-translate.svg
  documentation/static/img/pankod_footer_logo.png
  documentation/static/img/prettier.svg
  documentation/static/img/react-bootstrap.svg
  documentation/static/img/react-query.svg
  documentation/static/img/redux.svg
  documentation/static/img/reverbnation.svg
  documentation/static/img/sass.svg
  documentation/static/img/storybook.svg
  documentation/static/img/styled-components.png
  documentation/static/img/styled-system.svg
  documentation/static/img/superplate-logo.svg
  documentation/static/img/superplate-text.svg
  documentation/static/img/svgr.png
  documentation/static/img/swr.svg
  documentation/static/img/tailwind.svg
  documentation/static/img/testing-libraries.svg
  documentation/static/img/travis.svg
  documentation/static/img/undraw_docusaurus_mountain.svg
  documentation/static/img/undraw_docusaurus_react.svg
  documentation/static/img/undraw_docusaurus_tree.svg
  documentation/static/img/webdriverio.svg
Labels: auto-merge, pr-ready

#205 lint-staged ESLint warning
  documentation/docs/linter/lint-staged.md
  documentation/docs/storybook.md
Labels: auto-merge, pr-ready

#206 Fix testing description
  documentation/docs/axios.md
  documentation/docs/e2e-testing/cypress.md
  documentation/docs/e2e-testing/wdio.md
Labels: auto-merge, pr-ready

#212 Landing fix
  documentation/src/css/custom.css
  documentation/src/pages/index.js
  documentation/src/pages/styles.module.css
  documentation/static/img/cli.gif
  documentation/static/img/code.png
  documentation/static/img/code.svg
  documentation/static/img/superplate-text.svg
Labels: auto-merge, pr-ready

#217 add note for build-storybook
  documentation/docs/storybook.md
Labels: auto-merge, pr-ready

#204 Add readme badges
  README.MD
  images/available.png
  images/banner.png
  images/integrations.png
  images/plugins.png
Labels: auto-merge, pr-ready, review-required

#215 Add quick start
  documentation/docs/quick-start.md
Labels: auto-merge, pr-ready

#218 Add globalTypes warning to Apollo docs
  documentation/docs/apollo-graphql.md
Labels: auto-merge, pr-ready, review-required

#213 Update Bootstrap docs
  documentation/docs/bootstrap.md
Labels: auto-merge, pr-ready

#219 Fixed Landing issues
  documentation/docusaurus.config.js
  documentation/src/pages/index.js
Labels: auto-merge, pr-ready
